import Header from '@/components/Header';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Earth Worm',
  description: 'Generated by earth worm',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='flex flex-col'>
          <div className='mb-20'>
            <Header />
          </div>
          <div className='mb-18 mt-20'>{children}</div>
          <div className='fexed bottom-10 mt-12 pt-20 ml-24 pl-96'></div>
        </div>
      </body>
    </html>
  );
}
